# Generated by Django 2.2.19 on 2021-06-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210608_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='description1',
            new_name='description',
        ),
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(default='2021-01-01'),
            preserve_default=False,
        ),
    ]
